apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: automation-project-live-route
spec:
  http:
  - name: automation-project-live
    match:
      hosts:
      - "app.karl.com" # Ang atong live URL
      paths:
      - "/*"
    # --- MAO NI ANG SWITCH ---
    # Sa sugod, i-set nato tanan sa "blue"
    backends:
    - serviceName: automation-project-blue-internal
      servicePort: 80
      weight: 100 # 100% sa traffic kay adto sa BLUE
    - serviceName: automation-project-green-internal
      servicePort: 80
      weight: 0   # 0% sa traffic kay adto sa GREEN