apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: automation-project
  template:
    metadata:
      labels:
        app: automation-project
    spec:
      containers:
      - name: automation-project-container
        image: devopskarl/automation-project:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            # Maximum memory container can use before being killed (OOMKilled)
            memory: "512Mi" 
          requests:
            # Minimum memory guaranteed to the container (used for scheduling)
            memory: "128Mi"