# ----------------- Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
  labels:
    app: automation-project
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: automation-project
  template:
    metadata:
      labels:
        app: automation-project
    spec:
      containers:
        - name: automation-project-container
          image: devopskarl/automation-project:latest
          ports:
            - containerPort: 80

---
# ----------------- Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: automation-project-service
  labels:
    app: automation-project
spec:
  type: NodePort
  selector:
    app: automation-project
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # optional: fixed port for easy access
