# ----------------- Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app # This must match the Service's selector
  template: # <-- The blueprint for creating pods
    metadata:
      labels:
        app: my-app # This must match the Service's selector
    spec:
      containers:
      - name: my-app-container
        image: your/docker-image:tag
        ports:
        - containerPort: 80

---
# ----------------- Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app # <-- This finds the pods with the label "app: my-app"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80