apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automation-project
  template:
    metadata:
      labels:
        app: automation-project
    spec:
      containers:
      - name: automation-project-container
        image: devopskarl/automation-project:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always