# ----------------- Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automation-pods
  template:
    metadata:
      labels:
        app: my-app # Must match this selector
    spec:
      containers:
      - name: automation-container
        image: devopskarl/automation-project:latest

---
# ----------------- Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: automation-pods
  ports:
  - port: 80
    targetPort: 80