# ----------------- Deployment -----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app # This must match the Service's selector
  template:
    metadata:
      labels:
        app: my-app # This must match this selector
    spec:
      containers:
      - name: my-app-container
        image: your/docker-image:tag

---
# ----------------- Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app # Finds pods with this label
  ports:
  - port: 80
    targetPort: 80