apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: automation-project
  template:
    metadata:
      labels:
        app: automation-project
    spec:
      containers:
      - name: automation-project-container
        image: devopskarl/automation-project:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"     # Request 0.1 of a CPU
            memory: "128Mi"   # Request 128MB of RAM
            # ---
          limits:
            cpu: "500m"     # Limit to 0.5 of a CPU
            memory: "512Mi"   # Limit to 512MB of RAM