apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-project-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: automation-project
  template:
    metadata:
      labels:
        app: automation-project
    spec:
      containers:
      - name: automation-project-container
        image: devopskarl/automation-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: automation-project-service
spec:
  type: NodePort
  selector:
    app: automation-project
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080