apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automation-project-ingress
spec:
  rules:
  - host: "app.karl.com" # <-- Ang imong "live" URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: automation-project-service # <-- I-point sa atong "switch"
            port:
              number: 80