apiVersion: v1
kind: Service
metadata:
  name: automation-project-green-internal
spec:
  type: ClusterIP
  selector:
    app: automation-project
    version: green
  ports:
  - port: 80
    targetPort: 3000