apiVersion: v1
kind: Service
metadata:
  name: automation-project-green-internal
spec:
  type: ClusterIP # Internal only
  selector:
    app: automation-project
    version: green # <-- ALWAYS points to green
  ports:
  - port: 80
    targetPort: 3000