apiVersion: v1
kind: Service
metadata:
  name: automation-project-service
spec:
  type: NodePort
  selector:
    app: automation-project
  ports:
    - name: http
      port: 80           # Service port (inside the cluster)
      targetPort: 3000   # Podâ€™s container port
      nodePort: 30080    # Exposed port on each node for HAProxy
