apiVersion: v1
kind: Service
metadata:
  name: automation-project-service
spec:
  type: ClusterIP
  selector:
    app: automation-project
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 3000